robot:
  id: unitree_go2
  asset_config: data/robot/assets/multi-legged/unitree_go2/unitree_go2_cfg.py
  asset_symbol: UNITREE_GO2_CFG
  controlled_actuators: [legs]
  controlled_joints:
    - ".*_hip_joint"
    - ".*_thigh_joint"
    - ".*_calf_joint"
  base: base
  feet: [FL_foot, FR_foot, RL_foot, RR_foot]
  body_height: 0.25
  foot_clearance_height: 0.08

control:
  action_scale: 0.25

command:
  linear_x: [-1.0, 1.0]
  linear_y: [-1.0, 1.0]
  angular_z: [-1.0, 1.0]
